In [2]:
import numpy as np

Creating a ndarry object. We can use any of the methods on this object after it has been created.

In [6]:
array1= np.array([1, 2, 3, 4, 5])
print(array1)
print(type(array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dimensions in Arrays

In [10]:
#0-D arrays, these are also called Scalars. 

array2= np.array(42)
print(array2)
print(type(array2))

42
<class 'numpy.ndarray'>


In [40]:
#1-D array. These arrays have 0-D arrays as the elements. These are the most basic and common arrays.

array3= np.array([1, 2, 3, 4, 5, 6])
print(array3)

[1 2 3 4 5 6]


In [37]:
#2-D array. These arrays contain 1-D arrays as the elements. These are used to signify a matrix. (Also called 2nd order tensors)

array4= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
#print(array4)
#print(array4.ndim)

In [12]:
#3-D Array. These arrays have 2-D arrays as its elements

array5= np.array([[[1, 2, 3], [4,5,6]], [[1, 2, 3], [4,5,6]]])
print(array5)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check the number of Dimensions that our ndarray object has using the .ndim attribute

In [13]:
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)
print(array5.ndim)

0
1
2
3


Accessing the indexes of a np.array

In [21]:
print(array4[0])
print(array4[1])
print(array4[0] + array4[1])
new_var= array4[0] + array4[1]
print(type(new_var))
print(new_var.ndim)
#add_arr= np.array([[1, 2, 3, 4], [5, 6, 7]])
#print(add_arr[0] + add_arr[1])

#string_arr= np.array([["sammi", "ben"], ["aikerim", "valerie"]])
#print(string_arr[0] + string_arr[1])

[1 2 3]
[4 5 6]
[5 7 9]
<class 'numpy.ndarray'>
1


Slicing Numpy Arrays 

In [25]:
print(array4[2:])

[[ 7  8  9]
 [10 11 12]]


Arthimetic Operations
We can perform element-wise operations with scalar values


Aggregate Functions
We can perform aggregate
-min
-max
-mean


In [26]:
sum= array3 + 1
product= array3 * 2
division= array3 / 2 

print(sum)
print(product)
print(division)


[2 3 4 5 6]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [30]:
#.mean()
#.min()
#.max()
#.sum()
test_int= 10
sum= np.sum(array3)
min= np.min(array3)
max= np.max(array3)
average= np.mean(array3)

print(sum, min, max, average)
print(type(sum))
print(sum + min)
print(sum + test_int)

15 1 5 3.0
<class 'numpy.int32'>
16
25


Broadcasting with a 2D array

In [31]:
multidimension_broadcast= array4 * 2
print(multidimension_broadcast)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


Shaping with Numpy Arrays
- attribute shape 

In [44]:
print(array4.shape)
print(array5.shape)
print(np.shape(array4))
print(np.shape(array3))

(4, 3)
(2, 2, 3)
(4, 3)
(6,)


Reshaping an Array


In [42]:
print(np.reshape(array3, (2,3)))
print(array3.reshape(2,3))



[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


Transposing Arrays

In [48]:
#print(array3.transpose())
print(array4)
print(array4.transpose())

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Boolean Operations

In [53]:
a= np.array([1, 2, 3, 4, 5])
b= np.array([2, 2, 3, 3, 5])

c= a == b
d= np.array_equal(a, b)
print(c)
print(d)

[False  True  True False  True]
False


In [52]:
a= np.array([True, True, False, False])
b= np.array([True, False, True, False])

c= np.logical_and(a, b)
d= np.logical_or(a, b)
print(c)
print(d)

[ True False False False]
[ True  True  True False]


Sorting

In [60]:
a= np.array([3, 10, 7, 6, 8 , 31, 2, 5])
#descending hack
b= np.sort(a)[::-1]
c= a.sort()
#print(a)
print(b)
print(c)

print(a)

[31 10  8  7  6  5  3  2]
None
[ 2  3  5  6  7  8 10 31]
